const authStyles = {
  page: {
    minHeight: "100vh",
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "32px 16px",
  },
  card: {
    width: "100%",
    maxWidth: "430px",
    borderRadius: "24px",
    padding: "32px 28px",
    background: "rgba(255, 248, 235, 0.72)",
    backdropFilter: "blur(10px)",
    WebkitBackdropFilter: "blur(10px)",
    border: "1px solid rgba(255,255,255,0.35)",
    boxShadow: "0 10px 30px rgba(0,0,0,0.18)",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
  logo: {
    width: "84px",
    height: "84px",
    objectFit: "contain",
    marginBottom: "10px",
  },
  title: {
    margin: 0,
    marginBottom: "8px",
    fontSize: "28px",
    fontWeight: "700",
    color: "#222222",
    textAlign: "center",
  },
  subtitle: {
    margin: 0,
    marginBottom: "22px",
    fontSize: "14px",
    color: "#444444",
    textAlign: "center",
    lineHeight: 1.5,
  },
  content: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    gap: "16px",
  },
  inputWrapper: {
    width: "100%",
    position: "relative",
    display: "flex",
    alignItems: "center",
  },
  inputIcon: {
    position: "absolute",
    left: "14px",
    width: "18px",
    height: "18px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    pointerEvents: "none",
  },
  input: {
    width: "100%",
    height: "48px",
    borderRadius: "14px",
    border: "1px solid rgba(0, 0, 0, 0.10)",
    outline: "none",
    padding: "0 14px 0 44px",
    fontSize: "14px",
    color: "#1f1f1f",
    background: "rgba(255, 255, 255, 0.78)",
    boxSizing: "border-box",
  },
  select: {
    width: "100%",
    height: "48px",
    borderRadius: "14px",
    border: "1px solid rgba(0, 0, 0, 0.10)",
    outline: "none",
    padding: "0 14px",
    fontSize: "14px",
    color: "#1f1f1f",
    background: "rgba(255, 255, 255, 0.78)",
    boxSizing: "border-box",
  },
  rowLinks: {
    display: "flex",
    justifyContent: "space-between",
    gap: "12px",
    flexWrap: "wrap",
    width: "100%",
    marginTop: "-2px",
  },
  textLink: {
    fontSize: "13px",
    color: "#1d3557",
    cursor: "pointer",
    textDecoration: "none",
    fontWeight: "600",
  },
  button: {
    width: "100%",
    height: "48px",
    border: "none",
    borderRadius: "14px",
    background: "#2D6A4F",
    color: "#ffffff",
    fontSize: "15px",
    fontWeight: "700",
    cursor: "pointer",
    marginTop: "4px",
  },
  secondaryButton: {
    width: "100%",
    height: "48px",
    border: "none",
    borderRadius: "14px",
    background: "#2D6A4F",
    color: "#ffffff",
    fontSize: "15px",
    fontWeight: "700",
    cursor: "pointer",
  },
  error: {
    margin: 0,
    color: "#b00020",
    fontSize: "13px",
    textAlign: "center",
  },
  success: {
    margin: 0,
    color: "#1b5e20",
    fontSize: "13px",
    textAlign: "center",
  },
};

export default authStyles;